
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, CELLPHONE, PASSWORD, ROLE, IS_ENABLED) VALUES ('Juan1', 'Torres', 'juan1@hotmail.com', '3153724469', '1234', 'ADMIN', false);
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, CELLPHONE, PASSWORD, ROLE, IS_ENABLED) VALUES ('Juan2', 'Torres', 'juan2@hotmail.com', '3153724469', '1234', 'EXECUTOR', false);
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, CELLPHONE, PASSWORD, ROLE, IS_ENABLED) VALUES ('Juan3', 'Torres', 'juan3@hotmail.com', '3153724469', '1234', 'AUDITOR', false);
