DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (  
ID INT AUTO_INCREMENT  PRIMARY KEY,  
FIRSTNAME VARCHAR(50) NOT NULL,  
LASTNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,  
CELLPHONE VARCHAR(50),  
PASSWORD VARCHAR(150) NOT NULL,  
ROLE VARCHAR(50) NOT NULL,
IS_ENABLED BOOLEAN
);
